export default {
  cars: [
    {
      id: 1,
      name: 'Chevrolet',
      img: './images/car1.jpg',
      price: 50,
      model: '2018 model',
      manufacturer: 'General Motors (GM)',
      owner: 'John Doe',
      created_on: '17/5/2019',
      status: 'available',
      state: 'new',
      body_type: 'car',
    },
    {
      id: 2,
      name: 'ferrari',
      img: './images/car1.jpg',
      price: 50,
      model: '2018 model',
      manufacturer: 'General Motors (GM)',
      owner: 'John Doe',
      created_on: '17/5/2019',
      status: 'available',
      state: 'new',
      body_type: 'car',
    },
    {
      id: 3,
      name: 'Mercedes Benz',
      img: './images/car1.jpg',
      price: 50,
      model: '2018 model',
      manufacturer: 'General Motors (GM)',
      owner: 'John Doe',
      created_on: '17/5/2019',
      status: 'available',
      state: 'old',
      body_type: 'truck',
    },
    {
      id: 4,
      name: 'Volkswagen',
      img: './images/car1.jpg',
      price: 50,
      model: '2018 model',
      manufacturer: 'General Motors (GM)',
      owner: 'John Doe',
      created_on: '17/5/2019',
      status: 'available',
      state: 'old',
      body_type: 'van',
    },
  ],
};
